# -*- coding: utf-8 -*-
"""Script_Output.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJoevE3mYtWeNYxifYjel9_VmgBzEb3X
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!pip install -r requirements.txt

!unzip /content/json_dataset-20221218T164328Z-001.zip

!unzip /content/test_data-20221217T032833Z-001.zip

!python /content/drive/MyDrive/Nlp_Final_Project/run_train.py

!python /content/drive/MyDrive/Nlp_Final_Project/run_prediction.py